// SAMPLE — Replace with Supabase queries once DB is configured
import type { Room, Testimonial } from "@/lib/types";

export const SAMPLE_ROOMS: Room[] = [
    {
        id: "room-001",
        name: "Jaffna Heritage Suite",
        slug: "jaffna-heritage-suite",
        category: "suite",
        description:
            "Our crown jewel — a sprawling corner suite dressed in carved teak, handwoven palmyra textiles, and original Dutch-colonial tile floors. Wake to the scent of frangipani from the private balcony overlooking our heritage garden.",
        size_sqft: 620,
        max_guests: 3,
        beds: "1 King Bed + 1 Sofa Bed",
        floor: 2,
        price_lkr: 28000,
        price_usd: 85,
        amenities: [
            "Private balcony",
            "Free Wi-Fi",
            "Air conditioning",
            "En-suite bath",
            "Heritage tub",
            "Smart TV",
            "Mini bar",
            "Tea & coffee station",
            "Safe",
            "Daily housekeeping",
        ],
        images: [
            "/assets/DSC05363.JPG.jpeg",
            "/assets/DSC05365.JPG.jpeg",
        ],
        thumbnail: "/assets/DSC05363.JPG.jpeg",
        is_active: true,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
    },
    {
        id: "room-002",
        name: "Palmyra Deluxe Room",
        slug: "palmyra-deluxe-room",
        category: "deluxe",
        description:
            "Named for Jaffna's iconic palmyra palm, this sunlit deluxe room features terracotta accents, hand-block-printed linens, and a serene window seat for afternoon reading. The perfect retreat for couples or solo travellers.",
        size_sqft: 380,
        max_guests: 2,
        beds: "1 King Bed",
        floor: 1,
        price_lkr: 16500,
        price_usd: 50,
        amenities: [
            "Free Wi-Fi",
            "Air conditioning",
            "En-suite bath",
            "Smart TV",
            "Tea & coffee station",
            "Safe",
            "Daily housekeeping",
            "Welcome fruit basket",
        ],
        images: [
            "/assets/DSC05366.JPG.jpeg",
            "/assets/DSC05367.JPG.jpeg",
        ],
        thumbnail: "/assets/DSC05366.JPG.jpeg",
        is_active: true,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
    },
    {
        id: "room-003",
        name: "Lotus Superior Room",
        slug: "lotus-superior-room",
        category: "superior",
        description:
            "Airy and elegantly simple, the Lotus Superior room celebrates the sacred lotus through hand-painted wall murals and gold-accented fittings. Ideal for the mindful traveller seeking comfort without excess.",
        size_sqft: 290,
        max_guests: 2,
        beds: "1 Queen Bed",
        floor: 1,
        price_lkr: 12000,
        price_usd: 36,
        amenities: [
            "Free Wi-Fi",
            "Air conditioning",
            "En-suite bath",
            "Smart TV",
            "Tea & coffee station",
            "Daily housekeeping",
        ],
        images: [
            "/assets/DSC05368.JPG.jpeg",
            "/assets/DSC05370.JPG.jpeg",
        ],
        thumbnail: "/assets/DSC05368.JPG.jpeg",
        is_active: true,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
    },
    {
        id: "room-004",
        name: "Nallur Family Suite",
        slug: "nallur-family-suite",
        category: "family",
        description:
            "Spacious and joyful, designed for families. Two connecting rooms with twin beds for the children and a king suite for parents, connected by a shared heritage verandah. Named in honour of the sacred Nallur Kandaswamy Kovil.",
        size_sqft: 780,
        max_guests: 5,
        beds: "1 King Bed + 2 Twin Beds",
        floor: 2,
        price_lkr: 35000,
        price_usd: 106,
        amenities: [
            "Connecting rooms",
            "Private verandah",
            "Free Wi-Fi",
            "Air conditioning",
            "2 En-suite baths",
            "Smart TV",
            "Mini bar",
            "Tea & coffee station",
            "Safe",
            "Daily housekeeping",
            "Children's welcome pack",
        ],
        images: [
            "/assets/DSC05371.JPG.jpeg",
            "/assets/DSC05372.JPG.jpeg",
        ],
        thumbnail: "/assets/DSC05371.JPG.jpeg",
        is_active: true,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
    },
];

export const SAMPLE_TESTIMONIALS: Testimonial[] = [
    {
        id: "t-001",
        guest_name: "Priya Krishnamurthy",
        guest_country: "Singapore",
        rating: 5,
        comment:
            "Staying at Loga was like stepping into a living museum of Jaffna culture. The kolam on the courtyard floor was freshly drawn every morning — a ritual that moved me deeply. The team's warmth is unmatched.",
        room_name: "Jaffna Heritage Suite",
        stay_date: "2024-12",
        is_featured: true,
    },
    {
        id: "t-002",
        guest_name: "Thomas & Sophie Müller",
        guest_country: "Germany",
        rating: 5,
        comment:
            "We came for the architecture and stayed for the food. The breakfast spread — string hoppers, coconut sambal, and jaggery tea — was the best meal of our three-week Sri Lanka trip. Absolutely magical.",
        room_name: "Palmyra Deluxe Room",
        stay_date: "2024-11",
        is_featured: true,
    },
    {
        id: "t-003",
        guest_name: "Ananya Rajan",
        guest_country: "India",
        rating: 5,
        comment:
            "As a Tamil, this place felt like coming home to a home I never knew I had. The carved doorways, the brass lamps lit at dusk, the jasmine garlands — every detail spoke of care and heritage. I wept when we left.",
        room_name: "Jaffna Heritage Suite",
        stay_date: "2025-01",
        is_featured: true,
    },
    {
        id: "t-004",
        guest_name: "James Whitfield",
        guest_country: "United Kingdom",
        rating: 5,
        comment:
            "Exceptional in every way. The property is immaculately kept, the rooms are cool even in Jaffna's heat, and the owner Loga herself was the warmest host I've encountered in 30 years of travel. Book directly — worth every rupee.",
        room_name: "Lotus Superior Room",
        stay_date: "2024-10",
        is_featured: false,
    },
];

export const AMENITIES_ICONS: Record<string, string> = {
    "Free Wi-Fi": "wifi",
    "Air conditioning": "wind",
    "En-suite bath": "bath",
    "Smart TV": "tv",
    "Mini bar": "wine",
    "Safe": "lock",
    "Daily housekeeping": "sparkles",
    "Private balcony": "sun",
    "Heritage tub": "droplets",
    "Tea & coffee station": "coffee",
    "Connecting rooms": "link",
    "Private verandah": "home",
};
